<?php
    $p4wsProgrammingLanguage = array(#version 1 beta / en desarrollo
        'container(div)/
            container(header)/
                block(h1)/\(h1)
            \(header)
            nlcontainer(section)/
                container(table)/
                    container(thead)/
                        container(tr)/
                            nblock(th)/\(th)
                        \(tr)
                    \(thead)
                    nlcontainer(tbody)/
                        nlcontainer(tr)/
                            nblock(td)/\(td)
                        \(tr)
                    \(tbody)
                    nlcontainer(tfoot)/
                        container(tr)/
                            block(th)/\(th)
                        \(tr)
                    \(tfoot)
                \(table)
            \(section)
            nlcontainer(section)/\(section)
            nlcontainer(footer)/\(footer)
        \(div)
    ');
?>